# Generated by Django 3.1.7 on 2021-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211013_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=110),
        ),
        migrations.AddField(
            model_name='task',
            name='surname',
            field=models.CharField(default='', max_length=145),
        ),
    ]
