# Generated by Django 3.1.7 on 2021-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211013_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='surname',
            field=models.CharField(default='', max_length=145),
        ),
    ]
